ci(workflows): sync with fredrikaverpil/github

diff --git a/Taskfile.lua.yml b/Taskfile.lua.yml
--- a/Taskfile.lua.yml
+++ b/Taskfile.lua.yml
@@ -8,10 +8,10 @@ vars:
   TOOLS_DIR:
     sh: |
       git_root=$(git rev-parse --show-toplevel 2>/dev/null)
-      if [ $? -eq 0 ] && [ -d "$git_root/tools" ]; then
-        echo "$git_root/tools"
+      if [ $? -eq 0 ] && [ -d "$git_root/.tools" ]; then
+        echo "$git_root/.tools"
       else
-        echo "Error: Could not find tools directory in git root" >&2
+        echo "Error: Could not find .tools directory in git root" >&2
         exit 1
       fi
 
@@ -28,7 +28,7 @@ tasks:
       - stylua --config-path stylua.toml --check .
 
   install-stylua:
-    desc: Install stylua using version from tools/Cargo.toml
+    desc: Install stylua using version from .tools/Cargo.toml
     aliases: ["install"]
     dir: '{{.TOOLS_DIR}}'
     cmds:
